local wk = require("which-key")

wk.setup({})

wk.add({
	{ "<C-k>",      desc = "Signature Help" },
	{ "K",          desc = "Definition Hover" },
	{ "<leader>a",  desc = "Aerial" },
	{ "<leader>c",  desc = "CodeCompanion" },
	{ "<leader>cn", "<cmd>CodeCompanionChat<cr>",                        desc = "New Chat",           mode = { "v", "n" } },
	{ "<leader>ct", "<cmd>CodeCompanionChat Toggle<cr>",                 desc = "Toggle Chat" },
	{ "<leader>ci", "<cmd>CodeCompanion<cr>",                            desc = "Inline Prompt",      mode = "v" },
	{ "<leader>db", desc = "Toggle Breakpoint" },
	{ "<leader>dc", desc = "Continue" },
	{ "<leader>d",  group = "Debug" },
	{ "<leader>dt", desc = "Run Test" },
	{ "<leader>du", desc = "Toggle UI" },
	{ "<leader>fb", "<cmd>Telescope buffers<cr>",                        desc = "Find Buffer" },
	{ "<leader>ff", "<cmd>Telescope find_files<cr>",                     desc = "Find File" },
	{ "<leader>fg", "<cmd>Telescope live_grep<cr>",                      desc = "Live Grep" },
	{ "<leader>f",  group = "Find - Telescope" },
	{ "<leader>fh", "<cmd>Telescope help_tags<cr>",                      desc = "Help Tags" },
	{ "<leader>fj", "<cmd>Telescope jumplist<cr>",                       desc = "Jump List" },
	{ "<leader>fp", "<cmd>Octo pr list<cr>",                             desc = "PR List" },
	{ "<leader>gB", desc = "Git Blame Full" },
	{ "<leader>gb", desc = "Git Blame Line" },
	{ "<leader>gc", "<cmd>DiffviewClose<cr>",                            desc = "Close Diff" },
	{ "<leader>g",  group = "DiffView" },
	{ "<leader>gh", "<cmd>DiffviewFileHistory<cr>",                      desc = "Diff History" },
	{ "<leader>gH", "<cmd>DiffviewFileHistory --range=origin..HEAD<cr>", desc = "Diff History - Main" },
	{ "<leader>go", "<cmd>DiffviewOpen<cr>",                             desc = "Open Diff - Current" },
	{ "<leader>gO", "<cmd>DiffviewOpen origin/main...HEAD<cr>",          desc = "Open Diff - Main" },
	{ "<leader>lD", desc = "Declaration" },
	{ "<leader>ld", desc = "Definition" },
	{ "<leader>lf", desc = "Format" },
	{ "<leader>l",  group = "LSP" },
	{ "<leader>li", desc = "Implementation" },
	{ "<leader>ln", desc = "Rename" },
	{ "<leader>lr", desc = "References" },
	{ "<leader>lt", desc = "Type Definition" },
	{ "<leader>qe", desc = "Open Diagnostic Float" },
	{ "<leader>q",  group = "Diagnostics" },
	{ "<leader>qn", desc = "Next Diagnostic" },
	{ "<leader>qN", desc = "Previous Diagnostic" },
	{ "<leader>qq", desc = "Toggle Diagnostic List" },
	{ "<leader>qt", desc = "Toggle Inline Diagnostics" },
	{ "<leader>sb", desc = "Buffer Screenshot",                          mode = { "n", "v" } },
	{ "<leader>s",  group = "Screenshot",                                mode = { "n", "v" } },
	{ "<leader>ss", desc = "Selected Screenshot",                        mode = "v" },
	{ "<leader>sv", desc = "Visual Screenshot" },
	{ "<leader>t",  desc = "NeoTree" },
})
